[package]
name = "stub"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = {version = "1.0.91", features = ["full"]}
quote = "1.0.18"
macro-test = { git = "https://github.com/Warhorst/macro-test"}